// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// runTTPSolverC
List runTTPSolverC(String pathToFile, IntegerVector packing, IntegerMatrix initTours, int mu, int mutation, int maxEvaluations);
RcppExport SEXP _TTP_runTTPSolverC(SEXP pathToFileSEXP, SEXP packingSEXP, SEXP initToursSEXP, SEXP muSEXP, SEXP mutationSEXP, SEXP maxEvaluationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type pathToFile(pathToFileSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type packing(packingSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type initTours(initToursSEXP);
    Rcpp::traits::input_parameter< int >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type mutation(mutationSEXP);
    Rcpp::traits::input_parameter< int >::type maxEvaluations(maxEvaluationsSEXP);
    rcpp_result_gen = Rcpp::wrap(runTTPSolverC(pathToFile, packing, initTours, mu, mutation, maxEvaluations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TTP_runTTPSolverC", (DL_FUNC) &_TTP_runTTPSolverC, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_TTP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
