# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runWTSPSolverC <- function(pathToFile, packing, initTours, mu, mutation, objectiveType, survivalStrategy, maxEvaluations) {
    .Call('_TTP_runWTSPSolverC', PACKAGE = 'TTP', pathToFile, packing, initTours, mu, mutation, objectiveType, survivalStrategy, maxEvaluations)
}

tspC <- function(tour, D) {
    .Call('_TTP_tspC', PACKAGE = 'TTP', tour, D)
}

wtspC <- function(tour, problem, itemPackingPlan, itemWeights, itemAssignedNodes) {
    .Call('_TTP_wtspC', PACKAGE = 'TTP', tour, problem, itemPackingPlan, itemWeights, itemAssignedNodes)
}

ttpC <- function(tour, problem, itemPackingPlan, itemProfits, itemWeights, itemAssignedNodes) {
    .Call('_TTP_ttpC', PACKAGE = 'TTP', tour, problem, itemPackingPlan, itemProfits, itemWeights, itemAssignedNodes)
}

getMonotonicBlocksC <- function(mon) {
    .Call('_TTP_getMonotonicBlocksC', PACKAGE = 'TTP', mon)
}

