# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runWTSPSolverC <- function(pathToFile, packing, initTours, mu, mutation, survivalStrategy, maxEvaluations) {
    .Call('_TTP_runWTSPSolverC', PACKAGE = 'TTP', pathToFile, packing, initTours, mu, mutation, survivalStrategy, maxEvaluations)
}

